// Relative import to be able to reuse the C sources.
// See the comment in ../flutter_lua_bridge.podspec for more information.

#include "../../src/lua/src/lapi.c"
#include "../../src/lua/src/lauxlib.c"
#include "../../src/lua/src/lbaselib.c"
#include "../../src/lua/src/lcode.c"
#include "../../src/lua/src/lcorolib.c"
#include "../../src/lua/src/lctype.c"
#include "../../src/lua/src/ldblib.c"
#include "../../src/lua/src/ldebug.c"
#include "../../src/lua/src/ldo.c"
#include "../../src/lua/src/ldump.c"
#include "../../src/lua/src/lfunc.c"
#include "../../src/lua/src/lgc.c"
#include "../../src/lua/src/linit.c"
#include "../../src/lua/src/liolib.c"
#include "../../src/lua/src/llex.c"
#include "../../src/lua/src/lmathlib.c"
#include "../../src/lua/src/lmem.c"
#include "../../src/lua/src/loadlib.c"
#include "../../src/lua/src/lobject.c"
#include "../../src/lua/src/lopcodes.c"
#include "../../src/lua/src/loslib.c"
#include "../../src/lua/src/lparser.c"
#include "../../src/lua/src/lstate.c"
#include "../../src/lua/src/lstring.c"
#include "../../src/lua/src/lstrlib.c"
#include "../../src/lua/src/ltable.c"
#include "../../src/lua/src/ltablib.c"
#include "../../src/lua/src/ltm.c"
#include "../../src/lua/src/lua.c"
#include "../../src/lua/src/lundump.c"
#include "../../src/lua/src/lutf8lib.c"
#include "../../src/lua/src/lvm.c"
#include "../../src/lua/src/lzio.c"
