name: flutter_lua_bridge_workspace
description: Workspace for flutter_lua_bridge monorepo
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - flutter_lua_bridge
  - flutter_lua_shim
  - example
