name: flutter_lua_bridge_workspace
description: Workspace for flutter_lua_bridge monorepo
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - legacy/flutter_lua_bridge
  - legacy/flutter_lua_shim
  - examples/example
  - examples/example_lua_url
