-- Lua 5.5 C API 定义
-- 自动生成，不要手动修改
-- 生成时间: 2026-03-10 15:16:08

local M = {}

-- C API 函数 (124 个)
M.c_api = {
  {
    name = "lua_absindex",
    signature = "int lua_absindex (lua_State *L, int idx);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the acceptable index idx into an equivalent absolute index (that is, one that does not depend on the stack size).",
  },
  {
    name = "lua_arith",
    signature = "void lua_arith (lua_State *L, int op);",
    pops = "(2|1)",
    pushes = "1",
    errors = "e",
    description = "Performs an arithmetic or bitwise operation over the two values (or one, in the case of negations) at the top of the stack, with the value on the top being the second operand, pops these values, and pushes the result of the operation. The function follows the semantics of the corresponding Lua operator (that is, it may call metamethods). > The value of op must be one of the following constants: l> i>LUA_OPADD: performs addition (+)li> i>LUA_OPSUB: performs subtraction (-)li> i>LUA_OPMUL: perf...",
  },
  {
    name = "lua_atpanic",
    signature = "lua_CFunction lua_atpanic (lua_State *L, lua_CFunction panicf);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Sets a new panic function and returns the old one (see &sect;4.4).",
  },
  {
    name = "lua_call",
    signature = "void lua_call (lua_State *L, int nargs, int nresults);",
    pops = "(nargs+1)",
    pushes = "nresults",
    errors = "e",
    description = "Calls a function. Like regular Lua calls, lua_call respects the __call metamethod. So, here the word \"function\" means any callable value. > To do a call you must use the following protocol: first, the function to be called is pushed onto the stack; then, the arguments to the call are pushed in direct order; that is, the first argument is pushed first. Finally you call lua_call; nargs is the number of arguments that you pushed onto the stack. When the function returns, all arguments and the fu...",
  },
  {
    name = "lua_callk",
    signature = "void lua_callk (lua_State *L, int nargs, int nresults, lua_KContext ctx, lua_KFunction k);",
    pops = "(nargs + 1)",
    pushes = "nresults",
    errors = "e",
    description = "This function behaves exactly like lua_call, but allows the called function to yield (see &sect;4.5).",
  },
  {
    name = "lua_checkstack",
    signature = "int lua_checkstack (lua_State *L, int n);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Ensures that the stack has space for at least n extra elements, that is, that you can safely push up to n values into it. It returns false if it cannot fulfill the request, either because it would cause the stack to be greater than a fixed maximum size (typically at least several thousand elements) or because it cannot allocate memory for the extra space. This function never shrinks the stack; if the stack already has space for the extra elements, it is left unchanged.",
  },
  {
    name = "lua_close",
    signature = "void lua_close (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Close all active to-be-closed variables in the main thread, release all objects in the given Lua state (calling the corresponding garbage-collection metamethods, if any), and frees all dynamic memory used by this state. > On several platforms, you may not need to call this function, because all resources are naturally released when the host program ends. On the other hand, long-running programs that create multiple states, such as daemons or web servers, will probably need to close states as ...",
  },
  {
    name = "lua_closeslot",
    signature = "void lua_closeslot (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "e",
    description = "Close the to-be-closed slot at the given index and set its value to nil. The index must be the last index previously marked to be closed (see lua_toclose) that is still active (that is, not closed yet). > A __close metamethod cannot yield when called through this function.",
  },
  {
    name = "lua_closethread",
    signature = "int lua_closethread (lua_State *L, lua_State *from);",
    pops = "0",
    pushes = "?",
    errors = "-",
    description = "Resets a thread, cleaning its call stack and closing all pending to-be-closed variables. The parameter from represents the coroutine that is resetting L. If there is no such coroutine, this parameter can be NULL. > Unless L is equal to from, the call returns a status code: LUA_OK for no errors in the thread (either the original error that stopped the thread or errors in closing methods), or an error status otherwise. In case of error, the error object is put on the top of the stack. > If L is...",
  },
  {
    name = "lua_compare",
    signature = "int lua_compare (lua_State *L, int index1, int index2, int op);",
    pops = "0",
    pushes = "0",
    errors = "e",
    description = "Compares two Lua values. Returns 1 if the value at index index1 satisfies op when compared with the value at index index2, following the semantics of the corresponding Lua operator (that is, it may call metamethods). Otherwise returns 0. Also returns 0 if any of the indices is not valid. > The value of op must be one of the following constants: l> i>LUA_OPEQ: compares for equality (==)li> i>LUA_OPLT: compares for less than (li> i>LUA_OPLE: compares for less or equal ()li> ul>",
  },
  {
    name = "lua_concat",
    signature = "void lua_concat (lua_State *L, int n);",
    pops = "n",
    pushes = "1",
    errors = "e",
    description = "Concatenates the n values at the top of the stack, pops them, and leaves the result on the top. If n is 1, the result is the single value on the stack (that is, the function does nothing); if n is 0, the result is the empty string. Concatenation is performed following the usual semantics of Lua (see &sect;3.4.6).",
  },
  {
    name = "lua_copy",
    signature = "void lua_copy (lua_State *L, int fromidx, int toidx);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Copies the element at index fromidx into the valid index toidx, replacing the value at that position. Values at other positions are not affected.",
  },
  {
    name = "lua_createtable",
    signature = "void lua_createtable (lua_State *L, int nseq, int nrec);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates a new empty table and pushes it onto the stack. Parameter nseq is a hint for how many elements the table will have as a sequence; parameter nrec is a hint for how many other elements the table will have. Lua may use these hints to preallocate memory for the new table. This preallocation may help performance when you know in advance how many elements the table will have. Otherwise you should use the function lua_newtable.",
  },
  {
    name = "lua_dump",
    signature = "int lua_dump (lua_State *L, lua_Writer writer, void *data, int strip);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Dumps a function as a binary chunk. Receives a Lua function on the top of the stack and produces a binary chunk that, if loaded again, results in a function equivalent to the one dumped. As it produces parts of the chunk, lua_dump calls function writer (see lua_Writer) with the given data to write them. > The function lua_dump fully preserves the Lua stack through the calls to the writer function, except that it may push some values for internal use before the first call, and it restores the ...",
  },
  {
    name = "lua_error",
    signature = "int lua_error (lua_State *L);",
    pops = "1",
    pushes = "0",
    errors = "v",
    description = "Raises a Lua error, using the value on the top of the stack as the error object. This function does a long jump, and therefore never returns (see luaL_error).",
  },
  {
    name = "lua_gc",
    signature = "int lua_gc (lua_State *L, int what, ...);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Controls the garbage collector. > This function performs several tasks, according to the value of the parameter what. For options that need extra arguments, they are listed after the option. l> i>LUA_GCCOLLECT: Performs a full garbage-collection cycle. li> i>LUA_GCSTOP: Stops the garbage collector. li> i>LUA_GCRESTART: Restarts the garbage collector. li> i>LUA_GCCOUNT: Returns the current amount of memory (in Kbytes) in use by Lua. li> i>LUA_GCCOUNTB: Returns the remainder of dividing the cur...",
  },
  {
    name = "lua_getallocf",
    signature = "lua_Alloc lua_getallocf (lua_State *L, void **ud);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the memory-allocator function of a given state. If ud is not NULL, Lua stores in *ud the opaque pointer given when the memory-allocator function was set.",
  },
  {
    name = "lua_getextraspace",
    signature = "void *lua_getextraspace (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns a pointer to a raw memory area associated with the given Lua state. The application can use this area for any purpose; Lua does not use it for anything. > Each new thread has this area initialized with a copy of the area of the main thread. > By default, this area has the size of a pointer to void, but you can recompile Lua with a different size for this area. (See LUA_EXTRASPACE in luaconf.h.)",
  },
  {
    name = "lua_getfield",
    signature = "int lua_getfield (lua_State *L, int index, const char *k);",
    pops = "0",
    pushes = "1",
    errors = "e",
    description = "Pushes onto the stack the value t[k], where t is the value at the given index. As in Lua, this function may trigger a metamethod for the \"index\" event (see &sect;2.4). > Returns the type of the pushed value.",
  },
  {
    name = "lua_getglobal",
    signature = "int lua_getglobal (lua_State *L, const char *name);",
    pops = "0",
    pushes = "1",
    errors = "e",
    description = "Pushes onto the stack the value of the global name. Returns the type of that value.",
  },
  {
    name = "lua_gethook",
    signature = "lua_Hook lua_gethook (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the current hook function.",
  },
  {
    name = "lua_gethookcount",
    signature = "int lua_gethookcount (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the current hook count.",
  },
  {
    name = "lua_gethookmask",
    signature = "int lua_gethookmask (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the current hook mask.",
  },
  {
    name = "lua_geti",
    signature = "int lua_geti (lua_State *L, int index, lua_Integer i);",
    pops = "0",
    pushes = "1",
    errors = "e",
    description = "Pushes onto the stack the value t[i], where t is the value at the given index. As in Lua, this function may trigger a metamethod for the \"index\" event (see &sect;2.4). > Returns the type of the pushed value.",
  },
  {
    name = "lua_getinfo",
    signature = "int lua_getinfo (lua_State *L, const char *what, lua_Debug *ar);",
    pops = "(0|1)",
    pushes = "(0|1|2)",
    errors = "m",
    description = "Gets information about a specific function or function invocation. > To get information about a function invocation, the parameter ar must be a valid activation record that was filled by a previous call to lua_getstack or given as argument to a hook (see lua_Hook). > To get information about a function, you push it onto the stack and start the what string with the character '>'. (In that case, lua_getinfo pops the function from the top of the stack.) For instance, to know in which line a func...",
  },
  {
    name = "lua_getiuservalue",
    signature = "int lua_getiuservalue (lua_State *L, int index, int n);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes onto the stack the n-th user value associated with the full userdata at the given index and returns the type of the pushed value. > If the userdata does not have that value, pushes nil and returns LUA_TNONE.",
  },
  {
    name = "lua_getlocal",
    signature = "const char *lua_getlocal (lua_State *L, const lua_Debug *ar, int n);",
    pops = "0",
    pushes = "(0|1)",
    errors = "-",
    description = "Gets information about a local variable or a temporary value of a given activation record or a given function. > In the first case, the parameter ar must be a valid activation record that was filled by a previous call to lua_getstack or given as argument to a hook (see lua_Hook). The index n selects which local variable to inspect; see debug.getlocal for details about variable indices and names. > lua_getlocal pushes the variable's value onto the stack and returns its name. > In the second ca...",
  },
  {
    name = "lua_getmetatable",
    signature = "int lua_getmetatable (lua_State *L, int index);",
    pops = "0",
    pushes = "(0|1)",
    errors = "-",
    description = "If the value at the given index has a metatable, the function pushes that metatable onto the stack and returns 1. Otherwise, the function returns 0 and pushes nothing on the stack.",
  },
  {
    name = "lua_getstack",
    signature = "int lua_getstack (lua_State *L, int level, lua_Debug *ar);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Gets information about the interpreter runtime stack. > This function fills parts of a lua_Debug structure with an identification of the activation record of the function executing at a given level. Level 0 is the current running function, whereas level n+1 is the function that has called level n (except for tail calls, which do not count in the stack). When called with a level greater than the stack depth, lua_getstack returns 0; otherwise it returns 1.",
  },
  {
    name = "lua_gettable",
    signature = "int lua_gettable (lua_State *L, int index);",
    pops = "1",
    pushes = "1",
    errors = "e",
    description = "Pushes onto the stack the value t[k], where t is the value at the given index and k is the value on the top of the stack. > This function pops the key from the stack, pushing the resulting value in its place. As in Lua, this function may trigger a metamethod for the \"index\" event (see &sect;2.4). > Returns the type of the pushed value.",
  },
  {
    name = "lua_gettop",
    signature = "int lua_gettop (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the index of the top element in the stack. Because indices start at 1, this result is equal to the number of elements in the stack; in particular, 0 means an empty stack.",
  },
  {
    name = "lua_getupvalue",
    signature = "const char *lua_getupvalue (lua_State *L, int funcindex, int n);",
    pops = "0",
    pushes = "(0|1)",
    errors = "-",
    description = "Gets information about the n-th upvalue of the closure at index funcindex. It pushes the upvalue's value onto the stack and returns its name. Returns NULL (and pushes nothing) when the index n is greater than the number of upvalues. > See debug.getupvalue for more information about upvalues.",
  },
  {
    name = "lua_insert",
    signature = "void lua_insert (lua_State *L, int index);",
    pops = "1",
    pushes = "1",
    errors = "-",
    description = "Moves the top element into the given valid index, shifting up the elements above this index to open space. This function cannot be called with a pseudo-index, because a pseudo-index is not an actual stack position.",
  },
  {
    name = "lua_isboolean",
    signature = "int lua_isboolean (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a boolean, and 0 otherwise.",
  },
  {
    name = "lua_iscfunction",
    signature = "int lua_iscfunction (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a C function, and 0 otherwise.",
  },
  {
    name = "lua_isfunction",
    signature = "int lua_isfunction (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a function (either C or Lua), and 0 otherwise.",
  },
  {
    name = "lua_isinteger",
    signature = "int lua_isinteger (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is an integer (that is, the value is a number and is represented as an integer), and 0 otherwise.",
  },
  {
    name = "lua_islightuserdata",
    signature = "int lua_islightuserdata (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a light userdata, and 0 otherwise.",
  },
  {
    name = "lua_isnil",
    signature = "int lua_isnil (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is nil, and 0 otherwise.",
  },
  {
    name = "lua_isnone",
    signature = "int lua_isnone (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the given index is not valid, and 0 otherwise.",
  },
  {
    name = "lua_isnoneornil",
    signature = "int lua_isnoneornil (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the given index is not valid or if the value at this index is nil, and 0 otherwise.",
  },
  {
    name = "lua_isnumber",
    signature = "int lua_isnumber (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a number or a string convertible to a number, and 0 otherwise.",
  },
  {
    name = "lua_isstring",
    signature = "int lua_isstring (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a string or a number (which is always convertible to a string), and 0 otherwise.",
  },
  {
    name = "lua_istable",
    signature = "int lua_istable (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a table, and 0 otherwise.",
  },
  {
    name = "lua_isthread",
    signature = "int lua_isthread (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a thread, and 0 otherwise.",
  },
  {
    name = "lua_isuserdata",
    signature = "int lua_isuserdata (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the value at the given index is a userdata (either full or light), and 0 otherwise.",
  },
  {
    name = "lua_isyieldable",
    signature = "int lua_isyieldable (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the given coroutine can yield, and 0 otherwise.",
  },
  {
    name = "lua_len",
    signature = "void lua_len (lua_State *L, int index);",
    pops = "0",
    pushes = "1",
    errors = "e",
    description = "Returns the length of the value at the given index. It is equivalent to the '#' operator in Lua (see &sect;3.4.7) and may trigger a metamethod for the \"length\" event (see &sect;2.4). The result is pushed on the stack.",
  },
  {
    name = "lua_load",
    signature = "int lua_load (lua_State *L, lua_Reader reader, void *data, const char *chunkname, const char *mode);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Loads a Lua chunk without running it. If there are no errors, lua_load pushes the compiled chunk as a Lua function on top of the stack. Otherwise, it pushes an error message. > The lua_load function uses a user-supplied reader function to read the chunk (see lua_Reader). The data argument is an opaque value passed to the reader function. > The chunkname argument gives a name to the chunk, which is used for error messages and in debug information (see &sect;4.7). > lua_load automatically detec...",
  },
  {
    name = "lua_newstate",
    signature = "lua_State *lua_newstate (lua_Alloc f, void *ud, unsigned int seed);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Creates a new independent state and returns its main thread. Returns NULL if it cannot create the state (due to lack of memory). The argument f is the allocator function; Lua will do all memory allocation for this state through this function (see lua_Alloc). The second argument, ud, is an opaque pointer that Lua passes to the allocator in every call. The third argument, seed, is a seed for the hashing of strings.",
  },
  {
    name = "lua_newtable",
    signature = "void lua_newtable (lua_State *L);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates a new empty table and pushes it onto the stack. It is equivalent to lua_createtable(L,0,0).",
  },
  {
    name = "lua_newthread",
    signature = "lua_State *lua_newthread (lua_State *L);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates a new thread, pushes it on the stack, and returns a pointer to a lua_State that represents this new thread. The new thread returned by this function shares with the original thread its global environment, but has an independent execution stack. > Threads are subject to garbage collection, like any Lua object.",
  },
  {
    name = "lua_newuserdatauv",
    signature = "void *lua_newuserdatauv (lua_State *L, size_t size, int nuvalue);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "This function creates and pushes on the stack a new full userdata, with nuvalue associated Lua values, called user values, plus an associated block of raw memory with size bytes. (The user values can be set and read with the functions lua_setiuservalue and lua_getiuservalue.) > The function returns the address of the block of memory. Lua ensures that this address is valid as long as the corresponding userdata is alive (see &sect;2.5). Moreover, if the userdata is marked for finalization (see ...",
  },
  {
    name = "lua_next",
    signature = "int lua_next (lua_State *L, int index);",
    pops = "1",
    pushes = "(2|0)",
    errors = "v",
    description = "Pops a key from the stack, and pushes a key–value pair from the table at the given index, the \"next\" pair after the given key. If there are no more elements in the table, then lua_next returns 0 and pushes nothing. > A typical table traversal looks like this: re> /* table is in the stack at index 't' */ lua_pushnil(L); /* first key */ while (lua_next(L, t) != 0) { /* uses 'key' (at index -2) and 'value' (at index -1) */ printf(\"%s - %s\n\", lua_typename(L, lua_type(L, -2)), lua_typename(L, l...",
  },
  {
    name = "lua_numbertocstring",
    signature = "unsigned lua_numbertocstring (lua_State *L, int idx, char *buff);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the number at acceptable index idx to a string and puts the result in buff. The buffer must have a size of at least LUA_N2SBUFFSZ bytes. The conversion follows a non-specified format (see &sect;3.4.3). The function returns the number of bytes written to the buffer (including the final zero), or zero if the value at idx is not a number.",
  },
  {
    name = "lua_numbertointeger",
    signature = "unsigned lua_numbertocstring (lua_State *L, int idx, char *buff);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the number at acceptable index idx to a string and puts the result in buff. The buffer must have a size of at least LUA_N2SBUFFSZ bytes. The conversion follows a non-specified format (see &sect;3.4.3). The function returns the number of bytes written to the buffer (including the final zero), or zero if the value at idx is not a number.",
  },
  {
    name = "lua_pcall",
    signature = "int lua_pcall (lua_State *L, int nargs, int nresults, int msgh);",
    pops = "(nargs + 1)",
    pushes = "(nresults|1)",
    errors = "-",
    description = "Calls a function (or a callable object) in protected mode. > Both nargs and nresults have the same meaning as in lua_call. If there are no errors during the call, lua_pcall behaves exactly like lua_call. However, if there is any error, lua_pcall catches it, pushes a single value on the stack (the error object), and returns an error code. Like lua_call, lua_pcall always removes the function and its arguments from the stack. > If msgh is 0, then the error object returned on the stack is exactly...",
  },
  {
    name = "lua_pcallk",
    signature = "int lua_pcallk (lua_State *L, int nargs, int nresults, int msgh, lua_KContext ctx, lua_KFunction k);",
    pops = "(nargs + 1)",
    pushes = "(nresults|1)",
    errors = "-",
    description = "This function behaves exactly like lua_pcall, except that it allows the called function to yield (see &sect;4.5).",
  },
  {
    name = "lua_pop",
    signature = "void lua_pop (lua_State *L, int n);",
    pops = "n",
    pushes = "0",
    errors = "e",
    description = "Pops n elements from the stack. It is implemented as a macro over lua_settop.",
  },
  {
    name = "lua_pushboolean",
    signature = "void lua_pushboolean (lua_State *L, int b);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes a boolean value with value b onto the stack.",
  },
  {
    name = "lua_pushcclosure",
    signature = "void lua_pushcclosure (lua_State *L, lua_CFunction fn, int n);",
    pops = "n",
    pushes = "1",
    errors = "m",
    description = "Pushes a new C closure onto the stack. This function receives a pointer to a C function and pushes onto the stack a Lua value of type function that, when called, invokes the corresponding C function. The parameter n tells how many upvalues this function will have (see &sect;4.2). > Any function to be callable by Lua must follow the correct protocol to receive its parameters and return its results (see lua_CFunction). > When a C function is created, it is possible to associate some values with...",
  },
  {
    name = "lua_pushcfunction",
    signature = "void lua_pushcfunction (lua_State *L, lua_CFunction f);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes a C function onto the stack. This function is equivalent to lua_pushcclosure with no upvalues.",
  },
  {
    name = "lua_pushexternalstring",
    signature = "const char *lua_pushexternalstring (lua_State *L, const char *s, size_t len, lua_Alloc falloc, void *ud);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates an external string, that is, a string that uses memory not managed by Lua. The pointer s points to the external buffer holding the string content, and len is the length of the string. The string should have a zero at its end, that is, the condition s[len] == '\0' should hold. As with any string in Lua, the length must fit in a Lua integer. > If falloc is different from NULL, that function will be called by Lua when the external buffer is no longer needed. The contents of the buffer sh...",
  },
  {
    name = "lua_pushfstring",
    signature = "const char *lua_pushfstring (lua_State *L, const char *fmt, ...);",
    pops = "0",
    pushes = "1",
    errors = "v",
    description = "Pushes onto the stack a formatted string and returns a pointer to this string (see &sect;4.1.3). The result is a copy of fmt with each conversion specifier replaced by a string representation of its respective extra argument. A conversion specifier (and its corresponding extra argument) can be '%%' (inserts the character '%'), '%s' (inserts a zero-terminated string, with no size restrictions), '%f' (inserts a lua_Number), '%I' (inserts a lua_Integer), '%p' (inserts a void pointer), '%d' (inse...",
  },
  {
    name = "lua_pushglobaltable",
    signature = "void lua_pushglobaltable (lua_State *L);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes the global environment onto the stack.",
  },
  {
    name = "lua_pushinteger",
    signature = "void lua_pushinteger (lua_State *L, lua_Integer n);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes an integer with value n onto the stack.",
  },
  {
    name = "lua_pushlightuserdata",
    signature = "void lua_pushlightuserdata (lua_State *L, void *p);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes a light userdata onto the stack. > Userdata represent C values in Lua. A light userdata represents a pointer, a void*. It is a value (like a number): you do not create it, it has no individual metatable, and it is not collected (as it was never created). A light userdata is equal to \"any\" light userdata with the same C address.",
  },
  {
    name = "lua_pushliteral",
    signature = "const char *lua_pushliteral (lua_State *L, const char *s);",
    pops = "0",
    pushes = "1",
    errors = "v",
    description = "This macro is equivalent to lua_pushstring, but should be used only when s is a literal string. (Lua may optimize this case.)",
  },
  {
    name = "lua_pushlstring",
    signature = "const char *lua_pushlstring (lua_State *L, const char *s, size_t len);",
    pops = "0",
    pushes = "1",
    errors = "v",
    description = "Pushes the string pointed to by s with size len onto the stack. Lua will make or reuse an internal copy of the given string, so the memory at s can be freed or reused immediately after the function returns. The string can contain any binary data, including embedded zeros. > Returns a pointer to the internal copy of the string (see &sect;4.1.3). > Besides memory allocation errors, this function may raise an error if the string is too large.",
  },
  {
    name = "lua_pushnil",
    signature = "void lua_pushnil (lua_State *L);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes a nil value onto the stack.",
  },
  {
    name = "lua_pushnumber",
    signature = "void lua_pushnumber (lua_State *L, lua_Number n);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes a float with value n onto the stack.",
  },
  {
    name = "lua_pushstring",
    signature = "const char *lua_pushstring (lua_State *L, const char *s);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Pushes the zero-terminated string pointed to by s onto the stack. Lua will make or reuse an internal copy of the given string, so the memory at s can be freed or reused immediately after the function returns. > Returns a pointer to the internal copy of the string (see &sect;4.1.3). > If s is NULL, pushes nil and returns NULL.",
  },
  {
    name = "lua_pushthread",
    signature = "int lua_pushthread (lua_State *L);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes the thread represented by L onto the stack. Returns 1 if this thread is the main thread of its state.",
  },
  {
    name = "lua_pushvalue",
    signature = "void lua_pushvalue (lua_State *L, int index);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes a copy of the element at the given index onto the stack.",
  },
  {
    name = "lua_pushvfstring",
    signature = "const char *lua_pushvfstring (lua_State *L, const char *fmt, va_list argp);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Equivalent to lua_pushfstring, except that it receives a va_list instead of a variable number of arguments, and it does not raise errors. Instead, in case of errors it pushes the error message and returns NULL.",
  },
  {
    name = "lua_rawequal",
    signature = "int lua_rawequal (lua_State *L, int index1, int index2);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns 1 if the two values in indices index1 and index2 are primitively equal (that is, equal without calling the __eq metamethod). Otherwise returns 0. Also returns 0 if any of the indices are not valid.",
  },
  {
    name = "lua_rawget",
    signature = "int lua_rawget (lua_State *L, int index);",
    pops = "1",
    pushes = "1",
    errors = "-",
    description = "Similar to lua_gettable, but does a raw access (i.e., without metamethods). The value at index must be a table.",
  },
  {
    name = "lua_rawgeti",
    signature = "int lua_rawgeti (lua_State *L, int index, lua_Integer n);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes onto the stack the value t[n], where t is the table at the given index. The access is raw, that is, it does not use the __index metavalue. > Returns the type of the pushed value.",
  },
  {
    name = "lua_rawgetp",
    signature = "int lua_rawgetp (lua_State *L, int index, const void *p);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes onto the stack the value t[k], where t is the table at the given index and k is the pointer p represented as a light userdata. The access is raw; that is, it does not use the __index metavalue. > Returns the type of the pushed value.",
  },
  {
    name = "lua_rawlen",
    signature = "lua_Unsigned lua_rawlen (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the raw \"length\" of the value at the given index: for strings, this is the string length; for tables, this is the result of the length operator ('#') with no metamethods; for userdata, this is the size of the block of memory allocated for the userdata. For other values, this call returns 0.",
  },
  {
    name = "lua_rawset",
    signature = "void lua_rawset (lua_State *L, int index);",
    pops = "2",
    pushes = "0",
    errors = "m",
    description = "Similar to lua_settable, but does a raw assignment (i.e., without metamethods). The value at index must be a table.",
  },
  {
    name = "lua_rawseti",
    signature = "void lua_rawseti (lua_State *L, int index, lua_Integer i);",
    pops = "1",
    pushes = "0",
    errors = "m",
    description = "Does the equivalent of t[i] = v, where t is the table at the given index and v is the value on the top of the stack. > This function pops the value from the stack. The assignment is raw, that is, it does not use the __newindex metavalue.",
  },
  {
    name = "lua_rawsetp",
    signature = "void lua_rawsetp (lua_State *L, int index, const void *p);",
    pops = "1",
    pushes = "0",
    errors = "m",
    description = "Does the equivalent of t[p] = v, where t is the table at the given index, p is encoded as a light userdata, and v is the value on the top of the stack. > This function pops the value from the stack. The assignment is raw, that is, it does not use the __newindex metavalue.",
  },
  {
    name = "lua_register",
    signature = "void lua_register (lua_State *L, const char *name, lua_CFunction f);",
    pops = "0",
    pushes = "0",
    errors = "e",
    description = "Sets the C function f as the new value of global name. It is defined as a macro: re> #define lua_register(L,n,f) \\ (lua_pushcfunction(L, f), lua_setglobal(L, n)) pre>",
  },
  {
    name = "lua_remove",
    signature = "void lua_remove (lua_State *L, int index);",
    pops = "1",
    pushes = "0",
    errors = "-",
    description = "Removes the element at the given valid index, shifting down the elements above this index to fill the gap. This function cannot be called with a pseudo-index, because a pseudo-index is not an actual stack position.",
  },
  {
    name = "lua_replace",
    signature = "void lua_replace (lua_State *L, int index);",
    pops = "1",
    pushes = "0",
    errors = "-",
    description = "Moves the top element into the given valid index without shifting any element (therefore replacing the value at that given index), and then pops the top element.",
  },
  {
    name = "lua_resume",
    signature = "int lua_resume (lua_State *L, lua_State *from, int nargs, int *nresults);",
    pops = "?",
    pushes = "?",
    errors = "-",
    description = "Starts and resumes a coroutine in the given thread L. > To start a coroutine, you push the main function plus any arguments onto the empty stack of the thread. then you call lua_resume, with nargs being the number of arguments. The function returns when the coroutine suspends, finishes its execution, or raises an unprotected error. When it returns without errors, *nresults is updated and the top of the stack contains the *nresults values passed to lua_yield or returned by the body function. l...",
  },
  {
    name = "lua_rotate",
    signature = "void lua_rotate (lua_State *L, int idx, int n);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Rotates the stack elements between the valid index idx and the top of the stack. The elements are rotated n positions in the direction of the top, for a positive n, or -n positions in the direction of the bottom, for a negative n. The absolute value of n must not be greater than the size of the slice being rotated. This function cannot be called with a pseudo-index, because a pseudo-index is not an actual stack position.",
  },
  {
    name = "lua_setallocf",
    signature = "void lua_setallocf (lua_State *L, lua_Alloc f, void *ud);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Changes the allocator function of a given state to f with user data ud.",
  },
  {
    name = "lua_setfield",
    signature = "void lua_setfield (lua_State *L, int index, const char *k);",
    pops = "1",
    pushes = "0",
    errors = "e",
    description = "Does the equivalent to t[k] = v, where t is the value at the given index and v is the value on the top of the stack. > This function pops the value from the stack. As in Lua, this function may trigger a metamethod for the \"newindex\" event (see &sect;2.4).",
  },
  {
    name = "lua_setglobal",
    signature = "void lua_setglobal (lua_State *L, const char *name);",
    pops = "1",
    pushes = "0",
    errors = "e",
    description = "Pops a value from the stack and sets it as the new value of global name.",
  },
  {
    name = "lua_sethook",
    signature = "void lua_sethook (lua_State *L, lua_Hook f, int mask, int count);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Sets the debugging hook function. > Argument f is the hook function. mask specifies on which events the hook will be called: it is formed by a bitwise OR of the constants LUA_MASKCALL, LUA_MASKRET, LUA_MASKLINE, and LUA_MASKCOUNT. The count argument is only meaningful when the mask includes LUA_MASKCOUNT. For each event, the hook is called as explained below: l> i>The call hook: is called when the interpreter calls a function. The hook is called just after Lua enters the new function. li> i>T...",
  },
  {
    name = "lua_seti",
    signature = "void lua_seti (lua_State *L, int index, lua_Integer n);",
    pops = "1",
    pushes = "0",
    errors = "e",
    description = "Does the equivalent to t[n] = v, where t is the value at the given index and v is the value on the top of the stack. > This function pops the value from the stack. As in Lua, this function may trigger a metamethod for the \"newindex\" event (see &sect;2.4).",
  },
  {
    name = "lua_setiuservalue",
    signature = "int lua_setiuservalue (lua_State *L, int index, int n);",
    pops = "1",
    pushes = "0",
    errors = "-",
    description = "Pops a value from the stack and sets it as the new n-th user value associated to the full userdata at the given index. Returns 0 if the userdata does not have that value.",
  },
  {
    name = "lua_setlocal",
    signature = "const char *lua_setlocal (lua_State *L, const lua_Debug *ar, int n);",
    pops = "(0|1)",
    pushes = "0",
    errors = "-",
    description = "Sets the value of a local variable of a given activation record. It assigns the value on the top of the stack to the variable and returns its name. It also pops the value from the stack. > Returns NULL (and pops nothing) when the index is greater than the number of active local variables. > Parameters ar and n are as in the function lua_getlocal.",
  },
  {
    name = "lua_setmetatable",
    signature = "int lua_setmetatable (lua_State *L, int index);",
    pops = "1",
    pushes = "0",
    errors = "-",
    description = "Pops a table or nil from the stack and sets that value as the new metatable for the value at the given index. (nil means no metatable.) > (For historical reasons, this function returns an int, which now is always 1.)",
  },
  {
    name = "lua_settable",
    signature = "void lua_settable (lua_State *L, int index);",
    pops = "2",
    pushes = "0",
    errors = "e",
    description = "Does the equivalent to t[k] = v, where t is the value at the given index, v is the value on the top of the stack, and k is the value just below the top. > This function pops both the key and the value from the stack. As in Lua, this function may trigger a metamethod for the \"newindex\" event (see &sect;2.4).",
  },
  {
    name = "lua_settop",
    signature = "void lua_settop (lua_State *L, int index);",
    pops = "?",
    pushes = "?",
    errors = "e",
    description = "Receives any acceptable stack index, or 0, and sets the stack top to this index. If the new top is greater than the old one, then the new elements are filled with nil. If index is 0, then all stack elements are removed. > This function can run arbitrary code when removing an index marked as to-be-closed from the stack.",
  },
  {
    name = "lua_setupvalue",
    signature = "const char *lua_setupvalue (lua_State *L, int funcindex, int n);",
    pops = "(0|1)",
    pushes = "0",
    errors = "-",
    description = "Sets the value of a closure's upvalue. It assigns the value on the top of the stack to the upvalue and returns its name. It also pops the value from the stack. > Returns NULL (and pops nothing) when the index n is greater than the number of upvalues. > Parameters funcindex and n are as in the function lua_getupvalue.",
  },
  {
    name = "lua_setwarnf",
    signature = "void lua_setwarnf (lua_State *L, lua_WarnFunction f, void *ud);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Sets the warning function to be used by Lua to emit warnings (see lua_WarnFunction). The ud parameter sets the value ud passed to the warning function.",
  },
  {
    name = "lua_status",
    signature = "int lua_status (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the status of the thread L. > The status can be LUA_OK for a normal thread, an error code if the thread finished the execution of a lua_resume with an error, or LUA_YIELD if the thread is suspended. > You can call functions only in threads with status LUA_OK. You can resume threads with status LUA_OK (to start a new coroutine) or LUA_YIELD (to resume a coroutine).",
  },
  {
    name = "lua_stringtonumber",
    signature = "size_t lua_stringtonumber (lua_State *L, const char *s);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Converts the zero-terminated string s to a number, pushes that number into the stack, and returns the total size of the string, that is, its length plus one. The conversion can result in an integer or a float, according to the lexical conventions of Lua (see &sect;3.1). The string may have leading and trailing whitespaces and a sign. If the string is not a valid numeral, returns 0 and pushes nothing. (Note that the result can be used as a boolean, true if the conversion succeeds.)",
  },
  {
    name = "lua_toboolean",
    signature = "int lua_toboolean (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the Lua value at the given index to a C boolean value (0 or 1). Like all tests in Lua, lua_toboolean returns true for any Lua value different from false and nil; otherwise it returns false. (If you want to accept only actual boolean values, use lua_isboolean to test the value's type.)",
  },
  {
    name = "lua_tocfunction",
    signature = "lua_CFunction lua_tocfunction (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts a value at the given index to a C function. That value must be a C function; otherwise, returns NULL.",
  },
  {
    name = "lua_toclose",
    signature = "void lua_toclose (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Marks the given index in the stack as a to-be-closed slot (see &sect;3.3.8). Like a to-be-closed variable in Lua, the value at that slot in the stack will be closed when it goes out of scope. Here, in the context of a C function, to go out of scope means that the running function returns to Lua, or there is an error, or the slot is removed from the stack through lua_settop or lua_pop, or there is a call to lua_closeslot. A slot marked as to-be-closed should not be removed from the stack by an...",
  },
  {
    name = "lua_tointeger",
    signature = "lua_Integer lua_tointeger (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Equivalent to lua_tointegerx with isnum equal to NULL.",
  },
  {
    name = "lua_tointegerx",
    signature = "lua_Integer lua_tointegerx (lua_State *L, int index, int *isnum);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the Lua value at the given index to the signed integral type lua_Integer. The Lua value must be an integer, or a number or string convertible to an integer (see &sect;3.4.3); otherwise, lua_tointegerx returns 0. > If isnum is not NULL, its referent is assigned a boolean value that indicates whether the operation succeeded.",
  },
  {
    name = "lua_tolstring",
    signature = "const char *lua_tolstring (lua_State *L, int index, size_t *len);",
    pops = "0",
    pushes = "0",
    errors = "m",
    description = "Converts the Lua value at the given index to a C string. The Lua value must be a string or a number; otherwise, the function returns NULL. If the value is a number, then lua_tolstring also changes the actual value in the stack to a string. (This change confuses lua_next when lua_tolstring is applied to keys during a table traversal.) > If len is not NULL, the function sets *len with the string length. The returned C string always has a zero ('\0') after its last character, but can contain oth...",
  },
  {
    name = "lua_tonumber",
    signature = "lua_Number lua_tonumber (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Equivalent to lua_tonumberx with isnum equal to NULL.",
  },
  {
    name = "lua_tonumberx",
    signature = "lua_Number lua_tonumberx (lua_State *L, int index, int *isnum);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the Lua value at the given index to the C type lua_Number (see lua_Number). The Lua value must be a number or a string convertible to a number (see &sect;3.4.3); otherwise, lua_tonumberx returns 0. > If isnum is not NULL, its referent is assigned a boolean value that indicates whether the operation succeeded.",
  },
  {
    name = "lua_topointer",
    signature = "const void *lua_topointer (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the value at the given index to a generic C pointer (void*). The value can be a userdata, a table, a thread, a string, or a function; otherwise, lua_topointer returns NULL. Different objects will give different pointers. There is no way to convert the pointer back to its original value. > Typically this function is used only for hashing and debug information.",
  },
  {
    name = "lua_tostring",
    signature = "const char *lua_tostring (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "m",
    description = "Equivalent to lua_tolstring with len equal to NULL.",
  },
  {
    name = "lua_tothread",
    signature = "lua_State *lua_tothread (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Converts the value at the given index to a Lua thread (represented as lua_State*). This value must be a thread; otherwise, the function returns NULL.",
  },
  {
    name = "lua_touserdata",
    signature = "void *lua_touserdata (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "If the value at the given index is a full userdata, returns its memory-block address. If the value is a light userdata, returns its value (a pointer). Otherwise, returns NULL.",
  },
  {
    name = "lua_type",
    signature = "int lua_type (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the type of the value in the given valid index, or LUA_TNONE for a non-valid but acceptable index. The types returned by lua_type are coded by the following constants defined in lua.h: LUA_TNIL, LUA_TNUMBER, LUA_TBOOLEAN, LUA_TSTRING, LUA_TTABLE, LUA_TFUNCTION, LUA_TUSERDATA, LUA_TTHREAD, and LUA_TLIGHTUSERDATA.",
  },
  {
    name = "lua_typename",
    signature = "const char *lua_typename (lua_State *L, int tp);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the name of the type encoded by the value tp, which must be one the values returned by lua_type.",
  },
  {
    name = "lua_upvalueid",
    signature = "void *lua_upvalueid (lua_State *L, int funcindex, int n);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns a unique identifier for the upvalue numbered n from the closure at index funcindex. > These unique identifiers allow a program to check whether different closures share upvalues. Lua closures that share an upvalue (that is, that access a same external local variable) will return identical ids for those upvalue indices. > Parameters funcindex and n are as in the function lua_getupvalue, but n cannot be greater than the number of upvalues.",
  },
  {
    name = "lua_upvalueindex",
    signature = "int lua_upvalueindex (int i);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the pseudo-index that represents the i-th upvalue of the running function (see &sect;4.2). i must be in the range [1,256].",
  },
  {
    name = "lua_upvaluejoin",
    signature = "void lua_upvaluejoin (lua_State *L, int funcindex1, int n1, int funcindex2, int n2);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Make the n1-th upvalue of the Lua closure at index funcindex1 refer to the n2-th upvalue of the Lua closure at index funcindex2. 1>5 – The Auxiliary Libraryh1> > The auxiliary library provides several convenient functions to interface C with Lua. While the basic API provides the primitive functions for all interactions between C and Lua, the auxiliary library provides higher-level functions for some common tasks. > All functions and types from the auxiliary library are defined in the header...",
  },
  {
    name = "lua_version",
    signature = "lua_Number lua_version (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the version number of this core.",
  },
  {
    name = "lua_warning",
    signature = "void lua_warning (lua_State *L, const char *msg, int tocont);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Emits a warning with the given message. A message in a call with tocont true should be continued in another call to this function. > See warn for more details about warnings.",
  },
  {
    name = "lua_xmove",
    signature = "void lua_xmove (lua_State *from, lua_State *to, int n);",
    pops = "?",
    pushes = "?",
    errors = "-",
    description = "Exchange values between different threads of the same state. > This function pops n values from the stack from, and pushes them onto the stack to.",
  },
  {
    name = "lua_yield",
    signature = "int lua_yield (lua_State *L, int nresults);",
    pops = "?",
    pushes = "?",
    errors = "v",
    description = "This function is equivalent to lua_yieldk, but it has no continuation (see &sect;4.5). Therefore, when the thread resumes, it continues the function that called the function calling lua_yield. To avoid surprises, this function should be called only in a tail call.",
  },
  {
    name = "lua_yieldk",
    signature = "int lua_yieldk (lua_State *L, int nresults, lua_KContext ctx, lua_KFunction k);",
    pops = "?",
    pushes = "?",
    errors = "v",
    description = "Yields a coroutine (thread). > When a C function calls lua_yieldk, the running coroutine suspends its execution, and the call to lua_resume that started this coroutine returns. The parameter nresults is the number of values from the stack that will be passed as results to lua_resume. > When the coroutine is resumed again, Lua calls the given continuation function k to continue the execution of the C function that yielded (see &sect;4.5). This continuation function receives the same stack from...",
  },
}

-- Auxiliary Library 函数 (68 个)
M.aux_lib = {
  {
    name = "luaL_addchar",
    signature = "void luaL_addchar (luaL_Buffer *B, char c);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Adds the byte c to the buffer B (see luaL_Buffer).",
  },
  {
    name = "luaL_addgsub",
    signature = "const void luaL_addgsub (luaL_Buffer *B, const char *s, const char *p, const char *r);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Adds a copy of the string s to the buffer B (see luaL_Buffer), replacing any occurrence of the string p with the string r.",
  },
  {
    name = "luaL_addlstring",
    signature = "void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Adds the string pointed to by s with length l to the buffer B (see luaL_Buffer). The string can contain embedded zeros.",
  },
  {
    name = "luaL_addsize",
    signature = "void luaL_addsize (luaL_Buffer *B, size_t n);",
    pops = "?",
    pushes = "?",
    errors = "-",
    description = "Adds to the buffer B a string of length n previously copied to the buffer area (see luaL_prepbuffer).",
  },
  {
    name = "luaL_addstring",
    signature = "void luaL_addstring (luaL_Buffer *B, const char *s);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Adds the zero-terminated string pointed to by s to the buffer B (see luaL_Buffer).",
  },
  {
    name = "luaL_addvalue",
    signature = "void luaL_addvalue (luaL_Buffer *B);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Adds the value on the top of the stack to the buffer B (see luaL_Buffer). Pops the value. > This is the only function on string buffers that can (and must) be called with an extra element on the stack, which is the value to be added to the buffer.",
  },
  {
    name = "luaL_argcheck",
    signature = "void luaL_argcheck (lua_State *L, int cond, int arg, const char *extramsg);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether cond is true. If it is not, raises an error with a standard message (see luaL_argerror).",
  },
  {
    name = "luaL_argerror",
    signature = "int luaL_argerror (lua_State *L, int arg, const char *extramsg);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Raises an error reporting a problem with argument arg of the C function that called it, using a standard message that includes extramsg as a comment: re> bad argument #arg to 'funcname' (extramsg) pre>> This function never returns.",
  },
  {
    name = "luaL_argexpected",
    signature = "void luaL_argexpected (lua_State *L, int cond, int arg, const char *tname);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether cond is true. If it is not, raises an error about the type of the argument arg with a standard message (see luaL_typeerror).",
  },
  {
    name = "luaL_buffaddr",
    signature = "char *luaL_buffaddr (luaL_Buffer *B);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the address of the current content of buffer B (see luaL_Buffer). Note that any addition to the buffer may invalidate this address.",
  },
  {
    name = "luaL_buffinit",
    signature = "void luaL_buffinit (lua_State *L, luaL_Buffer *B);",
    pops = "0",
    pushes = "?",
    errors = "-",
    description = "Initializes a buffer B (see luaL_Buffer). This function does not allocate any space; the buffer must be declared as a variable.",
  },
  {
    name = "luaL_buffinitsize",
    signature = "char *luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Equivalent to the sequence luaL_buffinit, luaL_prepbuffsize.",
  },
  {
    name = "luaL_bufflen",
    signature = "size_t luaL_bufflen (luaL_Buffer *B);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the length of the current content of buffer B (see luaL_Buffer).",
  },
  {
    name = "luaL_buffsub",
    signature = "void luaL_buffsub (luaL_Buffer *B, int n);",
    pops = "?",
    pushes = "?",
    errors = "-",
    description = "Removes n bytes from the buffer B (see luaL_Buffer). The buffer must have at least that many bytes.",
  },
  {
    name = "luaL_callmeta",
    signature = "int luaL_callmeta (lua_State *L, int obj, const char *e);",
    pops = "0",
    pushes = "(0|1)",
    errors = "e",
    description = "Calls a metamethod. > If the object at index obj has a metatable and this metatable has a field e, this function calls this field passing the object as its only argument. In this case this function returns true and pushes onto the stack the value returned by the call. If there is no metatable or no metamethod, this function returns false without pushing any value on the stack.",
  },
  {
    name = "luaL_checkany",
    signature = "void luaL_checkany (lua_State *L, int arg);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function has an argument of any type (including nil) at position arg.",
  },
  {
    name = "luaL_checkinteger",
    signature = "lua_Integer luaL_checkinteger (lua_State *L, int arg);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function argument arg is an integer (or can be converted to an integer) and returns this integer.",
  },
  {
    name = "luaL_checklstring",
    signature = "const char *luaL_checklstring (lua_State *L, int arg, size_t *l);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function argument arg is a string and returns this string; if l is not NULL fills its referent with the string's length. > This function uses lua_tolstring to get its result, so all conversions and caveats of that function apply here.",
  },
  {
    name = "luaL_checknumber",
    signature = "lua_Number luaL_checknumber (lua_State *L, int arg);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function argument arg is a number and returns this number converted to a lua_Number.",
  },
  {
    name = "luaL_checkoption",
    signature = "int luaL_checkoption (lua_State *L, int arg, const char *def, const char *const lst[]);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function argument arg is a string and searches for this string in the array lst (which must be NULL-terminated). Returns the index in the array where the string was found. Raises an error if the argument is not a string or if the string cannot be found. > If def is not NULL, the function uses def as a default value when there is no argument arg or when this argument is nil. > This is a useful function for mapping strings to C enums. (The usual convention in Lua libraries is...",
  },
  {
    name = "luaL_checkstack",
    signature = "void luaL_checkstack (lua_State *L, int sz, const char *msg);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Grows the stack size to top + sz elements, raising an error if the stack cannot grow to that size. msg is an additional text to go into the error message (or NULL for no additional text).",
  },
  {
    name = "luaL_checkstring",
    signature = "const char *luaL_checkstring (lua_State *L, int arg);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function argument arg is a string and returns this string. > This function uses lua_tolstring to get its result, so all conversions and caveats of that function apply here.",
  },
  {
    name = "luaL_checktype",
    signature = "void luaL_checktype (lua_State *L, int arg, int t);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function argument arg has type t. See lua_type for the encoding of types for t.",
  },
  {
    name = "luaL_checkudata",
    signature = "void *luaL_checkudata (lua_State *L, int arg, const char *tname);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the function argument arg is a userdata of the type tname (see luaL_newmetatable) and returns the userdata's memory-block address (see lua_touserdata).",
  },
  {
    name = "luaL_checkversion",
    signature = "void luaL_checkversion (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Checks whether the code making the call and the Lua library being called are using the same version of Lua and the same numeric types.",
  },
  {
    name = "luaL_dofile",
    signature = "int luaL_dofile (lua_State *L, const char *filename);",
    pops = "0",
    pushes = "?",
    errors = "m",
    description = "Loads and runs the given file. It is defined as the following macro: re> (luaL_loadfile(L, filename) || lua_pcall(L, 0, LUA_MULTRET, 0)) pre>> It returns 0 (LUA_OK) if there are no errors, or 1 in case of errors. (Except for out-of-memory errors, which are raised.)",
  },
  {
    name = "luaL_dostring",
    signature = "int luaL_dostring (lua_State *L, const char *str);",
    pops = "0",
    pushes = "?",
    errors = "-",
    description = "Loads and runs the given string. It is defined as the following macro: re> (luaL_loadstring(L, str) || lua_pcall(L, 0, LUA_MULTRET, 0)) pre>> It returns 0 (LUA_OK) if there are no errors, or 1 in case of errors.",
  },
  {
    name = "luaL_error",
    signature = "int luaL_error (lua_State *L, const char *fmt, ...);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Raises an error. The error message format is given by fmt plus any extra arguments, following the same rules of lua_pushfstring. It also adds at the beginning of the message the file name and the line number where the error occurred, if this information is available. > This function never returns, but it is an idiom to use it in C functions as return luaL_error(args).",
  },
  {
    name = "luaL_execresult",
    signature = "int luaL_execresult (lua_State *L, int stat);",
    pops = "0",
    pushes = "3",
    errors = "m",
    description = "This function produces the return values for process-related functions in the standard library (os.execute and io.close).",
  },
  {
    name = "luaL_fileresult",
    signature = "int luaL_fileresult (lua_State *L, int stat, const char *fname);",
    pops = "0",
    pushes = "(1|3)",
    errors = "m",
    description = "This function produces the return values for file-related functions in the standard library (io.open, os.rename, file:seek, etc.).",
  },
  {
    name = "luaL_getmetafield",
    signature = "int luaL_getmetafield (lua_State *L, int obj, const char *e);",
    pops = "0",
    pushes = "(0|1)",
    errors = "m",
    description = "Pushes onto the stack the field e from the metatable of the object at index obj and returns the type of the pushed value. If the object does not have a metatable, or if the metatable does not have this field, pushes nothing and returns LUA_TNIL.",
  },
  {
    name = "luaL_getmetatable",
    signature = "int luaL_getmetatable (lua_State *L, const char *tname);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Pushes onto the stack the metatable associated with the name tname in the registry (see luaL_newmetatable), or nil if there is no metatable associated with that name. Returns the type of the pushed value.",
  },
  {
    name = "luaL_getsubtable",
    signature = "int luaL_getsubtable (lua_State *L, int idx, const char *fname);",
    pops = "0",
    pushes = "1",
    errors = "e",
    description = "Ensures that the value t[fname], where t is the value at index idx, is a table, and pushes that table onto the stack. Returns true if it finds a previous table there and false if it creates a new table.",
  },
  {
    name = "luaL_gsub",
    signature = "const char *luaL_gsub (lua_State *L, const char *s, const char *p, const char *r);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates a copy of string s, replacing any occurrence of the string p with the string r. Pushes the resulting string on the stack and returns it.",
  },
  {
    name = "luaL_len",
    signature = "lua_Integer luaL_len (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "e",
    description = "Returns the \"length\" of the value at the given index as a number; it is equivalent to the '#' operator in Lua (see &sect;3.4.7). Raises an error if the result of the operation is not an integer. (This case can only happen through metamethods.)",
  },
  {
    name = "luaL_loadbuffer",
    signature = "int luaL_loadbuffer (lua_State *L, const char *buff, size_t sz, const char *name);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Equivalent to luaL_loadbufferx with mode equal to NULL.",
  },
  {
    name = "luaL_loadbufferx",
    signature = "int luaL_loadbufferx (lua_State *L, const char *buff, size_t sz, const char *name, const char *mode);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Loads a buffer as a Lua chunk. This function uses lua_load to load the chunk in the buffer pointed to by buff with size sz. > This function returns the same results as lua_load. name is the chunk name, used for debug information and error messages. The string mode works as in the function lua_load. In particular, this function supports mode 'B' for fixed buffers.",
  },
  {
    name = "luaL_loadfile",
    signature = "int luaL_loadfile (lua_State *L, const char *filename);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Equivalent to luaL_loadfilex with mode equal to NULL.",
  },
  {
    name = "luaL_loadfilex",
    signature = "int luaL_loadfilex (lua_State *L, const char *filename, const char *mode);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Loads a file as a Lua chunk. This function uses lua_load to load the chunk in the file named filename. If filename is NULL, then it loads from the standard input. The first line in the file is ignored if it starts with a #. > The string mode works as in the function lua_load. > This function returns the same results as lua_load, or LUA_ERRFILE for file-related errors. > As lua_load, this function only loads the chunk; it does not run it.",
  },
  {
    name = "luaL_loadstring",
    signature = "int luaL_loadstring (lua_State *L, const char *s);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Loads a string as a Lua chunk. This function uses lua_load to load the chunk in the zero-terminated string s. > This function returns the same results as lua_load. > Also as lua_load, this function only loads the chunk; it does not run it.",
  },
  {
    name = "luaL_makeseed",
    signature = "unsigned int luaL_makeseed (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns a value with a weak attempt for randomness. The parameter L can be NULL if there is no Lua state available.",
  },
  {
    name = "luaL_newlib",
    signature = "void luaL_newlib (lua_State *L, const luaL_Reg l[]);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates a new table and registers there the functions in the list l. > It is implemented as the following macro: re> (luaL_newlibtable(L,l), luaL_setfuncs(L,l,0)) pre>> The array l must be the actual array, not a pointer to it.",
  },
  {
    name = "luaL_newlibtable",
    signature = "void luaL_newlibtable (lua_State *L, const luaL_Reg l[]);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates a new table with a size optimized to store all entries in the array l (but does not actually store them). It is intended to be used in conjunction with luaL_setfuncs (see luaL_newlib). > It is implemented as a macro. The array l must be the actual array, not a pointer to it.",
  },
  {
    name = "luaL_newmetatable",
    signature = "int luaL_newmetatable (lua_State *L, const char *tname);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "If the registry already has the key tname, returns 0. Otherwise, creates a new table to be used as a metatable for userdata, adds to this new table the pair __name = tname, adds to the registry the pair [tname] = new table, and returns 1. > In both cases, the function pushes onto the stack the final value associated with tname in the registry.",
  },
  {
    name = "luaL_newstate",
    signature = "lua_State *luaL_newstate (void);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Creates a new Lua state. It calls lua_newstate with luaL_alloc as the allocator function and the result of luaL_makeseed(NULL) as the seed, and then sets a warning function and a panic function (see &sect;4.4) that print messages to the standard error output. > Returns the new state, or NULL if there is a memory allocation error.",
  },
  {
    name = "luaL_openlibs",
    signature = "void luaL_openlibs (lua_State *L);",
    pops = "0",
    pushes = "0",
    errors = "e",
    description = "Opens all standard Lua libraries into the given state.",
  },
  {
    name = "luaL_openselectedlibs",
    signature = "void luaL_openselectedlibs (lua_State *L, int load, int preload);",
    pops = "0",
    pushes = "0",
    errors = "e",
    description = "Opens (loads) and preloads selected standard libraries into the state L. (To preload means to add the library loader into the table package.preload, so that the library can be required later by the program. Keep in mind that require itself is provided by the package library. If a program does not load that library, it will be unable to require anything.) > The integer load selects which libraries to load; the integer preload selects which to preload, among those not loaded. Both are masks for...",
  },
  {
    name = "luaL_opt",
    signature = "T luaL_opt (L, func, arg, dflt);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "This macro is defined as follows: re> (lua_isnoneornil(L,(arg)) ? (dflt) : func(L,(arg))) pre>> In words, if the argument arg is nil or absent, the macro results in the default dflt. Otherwise, it results in the result of calling func with the state L and the argument index arg as arguments. Note that it evaluates the expression dflt only if needed.",
  },
  {
    name = "luaL_optinteger",
    signature = "lua_Integer luaL_optinteger (lua_State *L, int arg, lua_Integer d);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "If the function argument arg is an integer (or it is convertible to an integer), returns this integer. If this argument is absent or is nil, returns d. Otherwise, raises an error.",
  },
  {
    name = "luaL_optlstring",
    signature = "const char *luaL_optlstring (lua_State *L, int arg, const char *d, size_t *l);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "If the function argument arg is a string, returns this string. If this argument is absent or is nil, returns d. Otherwise, raises an error. > If l is not NULL, fills its referent with the result's length. If the result is NULL (only possible when returning d and d == NULL), its length is considered zero. > This function uses lua_tolstring to get its result, so all conversions and caveats of that function apply here.",
  },
  {
    name = "luaL_optnumber",
    signature = "lua_Number luaL_optnumber (lua_State *L, int arg, lua_Number d);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "If the function argument arg is a number, returns this number as a lua_Number. If this argument is absent or is nil, returns d. Otherwise, raises an error.",
  },
  {
    name = "luaL_optstring",
    signature = "const char *luaL_optstring (lua_State *L, int arg, const char *d);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "If the function argument arg is a string, returns this string. If this argument is absent or is nil, returns d. Otherwise, raises an error.",
  },
  {
    name = "luaL_prepbuffer",
    signature = "char *luaL_prepbuffer (luaL_Buffer *B);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Equivalent to luaL_prepbuffsize with the predefined size LUAL_BUFFERSIZE.",
  },
  {
    name = "luaL_prepbuffsize",
    signature = "char *luaL_prepbuffsize (luaL_Buffer *B, size_t sz);",
    pops = "?",
    pushes = "?",
    errors = "m",
    description = "Returns an address to a space of size sz where you can copy a string to be added to buffer B (see luaL_Buffer). After copying the string into this space you must call luaL_addsize with the size of the string to actually add it to the buffer.",
  },
  {
    name = "luaL_pushfail",
    signature = "void luaL_pushfail (lua_State *L);",
    pops = "0",
    pushes = "1",
    errors = "-",
    description = "Pushes the fail value onto the stack (see &sect;6).",
  },
  {
    name = "luaL_pushresult",
    signature = "void luaL_pushresult (luaL_Buffer *B);",
    pops = "?",
    pushes = "1",
    errors = "m",
    description = "Finishes the use of buffer B leaving the final string on the top of the stack.",
  },
  {
    name = "luaL_pushresultsize",
    signature = "void luaL_pushresultsize (luaL_Buffer *B, size_t sz);",
    pops = "?",
    pushes = "1",
    errors = "m",
    description = "Equivalent to the sequence luaL_addsize, luaL_pushresult.",
  },
  {
    name = "luaL_ref",
    signature = "int luaL_ref (lua_State *L, int t);",
    pops = "1",
    pushes = "0",
    errors = "m",
    description = "Creates and returns a reference, in the table at index t, for the object on the top of the stack (and pops the object). > The reference system uses the integer keys of the table. A reference is a unique integer key; luaL_ref ensures the uniqueness of the keys it returns. The entry 1 is reserved for internal use. Before the first use of luaL_ref, the integer keys of the table should form a proper sequence (no holes), and the value at entry 1 should be false: nil if the sequence is empty, false...",
  },
  {
    name = "luaL_requiref",
    signature = "void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb);",
    pops = "0",
    pushes = "1",
    errors = "e",
    description = "If package.loaded[modname] is not true, calls the function openf with the string modname as an argument and sets the call result to package.loaded[modname], as if that function has been called through require. > If glb is true, also stores the module into the global variable modname. > Leaves a copy of the module on the stack.",
  },
  {
    name = "luaL_setfuncs",
    signature = "void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup);",
    pops = "nup",
    pushes = "0",
    errors = "m",
    description = "Registers all functions in the array l (see luaL_Reg) into the table on the top of the stack (below optional upvalues, see next). > When nup is not zero, all functions are created with nup upvalues, initialized with copies of the nup values previously pushed on the stack on top of the library table. These values are popped from the stack after the registration. > A function with a NULL value represents a placeholder, which is filled with false.",
  },
  {
    name = "luaL_setmetatable",
    signature = "void luaL_setmetatable (lua_State *L, const char *tname);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Sets the metatable of the object on the top of the stack as the metatable associated with name tname in the registry (see luaL_newmetatable).",
  },
  {
    name = "luaL_testudata",
    signature = "void *luaL_testudata (lua_State *L, int arg, const char *tname);",
    pops = "0",
    pushes = "0",
    errors = "m",
    description = "This function works like luaL_checkudata, except that, when the test fails, it returns NULL instead of raising an error.",
  },
  {
    name = "luaL_tolstring",
    signature = "const char *luaL_tolstring (lua_State *L, int idx, size_t *len);",
    pops = "0",
    pushes = "1",
    errors = "e",
    description = "Converts any Lua value at the given index to a C string in a reasonable format. The resulting string is pushed onto the stack and also returned by the function (see &sect;4.1.3). If len is not NULL, the function also sets *len with the string length. > If the value has a metatable with a __tostring field, then luaL_tolstring calls the corresponding metamethod with the value as argument, and uses the result of the call as its result.",
  },
  {
    name = "luaL_traceback",
    signature = "void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Creates and pushes a traceback of the stack L1. If msg is not NULL, it is appended at the beginning of the traceback. The level parameter tells at which level to start the traceback.",
  },
  {
    name = "luaL_typeerror",
    signature = "int luaL_typeerror (lua_State *L, int arg, const char *tname);",
    pops = "0",
    pushes = "0",
    errors = "v",
    description = "Raises a type error for the argument arg of the C function that called it, using a standard message; tname is a \"name\" for the expected type. This function never returns.",
  },
  {
    name = "luaL_typename",
    signature = "const char *luaL_typename (lua_State *L, int index);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Returns the name of the type of the value at the given index.",
  },
  {
    name = "luaL_unref",
    signature = "void luaL_unref (lua_State *L, int t, int ref);",
    pops = "0",
    pushes = "0",
    errors = "-",
    description = "Releases a reference (see luaL_ref). The integer ref must be either LUA_NOREF, LUA_REFNIL, or a reference previously returned by luaL_ref and not already released. If ref is either LUA_NOREF or LUA_REFNIL this function does nothing. Otherwise, the entry is removed from the table, so that the referred object can be collected and the reference ref can be used again by luaL_ref.",
  },
  {
    name = "luaL_where",
    signature = "void luaL_where (lua_State *L, int lvl);",
    pops = "0",
    pushes = "1",
    errors = "m",
    description = "Pushes onto the stack a string identifying the current position of the control at level lvl in the call stack. Typically this string has the following format: re> chunkname:currentline: pre>> Level 0 is the running function, level 1 is the function that called the running function, etc. > This function is used to build a prefix for error messages. 1>6 – The Standard Librariesh1> > The standard Lua libraries provide useful functions that are implemented in C through the C API. Some of these ...",
  },
}

return M